name: mobility_app
version: 1.0.0+1
publish_to: none
description: Schedules and other mobility types
environment: 
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  archive: ^3.1.2
  async: ^2.11.0
  bloc_test: ^9.0.0
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  external_app_launcher: ^3.1.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_native_splash: ^2.3.1
  flutter_typeahead: ^4.6.2
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: any
  json_serializable: ^6.7.0
  latlong2: ^0.8.1
  mockito: ^5.4.2
  path: any
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: any
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.11
  very_good_analysis: ^5.0.0+1

dev_dependencies: 
  build_runner: ^2.4.5
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.3
flutter:
  generate: true
  assets: 
    - assets/scooter.png
    - assets/bicycle.png
    - assets/bus.png
    - assets/scooter_low_battery.png
    - assets/public_transport/county_bus.png
    - assets/public_transport/ferry.png
    - assets/public_transport/train.png
    - assets/public_transport/tram.png
    - assets/public_transport/trolleybus.png
  uses-material-design: true
flutter_intl:
  enabled: true
