name: mobility_app
version: 1.0.0+1
publish_to: none
description: Schedules and other mobility types
environment: 
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  archive: ^3.1.2
  async: ^2.11.0
  auth_buttons: ^1.0.1+4
  bloc_test: ^9.0.0
  cloud_firestore: ^4.8.2
  collection: ^1.17.1
  device_info_plus: ^9.0.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_typeahead: ^4.6.2
  geolocator: ^9.0.2
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  google_sign_in: ^5.1.1
  http: ^0.13.5
  intl: any
  introduction_screen: ^3.1.11
  json_serializable: ^6.7.0
  latlong2: ^0.8.1
  logging: ^1.2.0
  mocktail: ^0.3.0
  onboarding_overlay: ^3.2.1
  path: any
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: any
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.11
  very_good_analysis: ^5.0.0+1

dev_dependencies: 
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  patrol: ^2.0.7
  pubspec_dependency_sorter: ^1.0.3

patrol:
  app_name: Yggert Nu
  android:
    package_name: com.oolaa.redefined.mobility.mobility_app

flutter: 
  assets: 
    - assets/bolt_scooter.png
    - assets/tuul_scooter.png
    - assets/bicycle.png
    - assets/bus.png
    - assets/scooter_low_battery.png
    - assets/public_transport/county_bus.png
    - assets/public_transport/ferry.png
    - assets/public_transport/train.png
    - assets/public_transport/tram.png
    - assets/public_transport/trolleybus.png
    - assets/default_avatar.png
    - assets/launcher_icon/launcher_icon.png
    - assets/intro/intro_city.png
    - assets/intro/intro_bus_stop.png
    - assets/intro/intro_end.png
    - assets/intro/intro_theme_change.png
    - assets/intro/intro_google_sign_in.png
    - assets/intro/intro_please_note.png
    - assets/hoog_scooter.png
  generate: true
  uses-material-design: true
flutter_intl: 
  enabled: true
