name: mobility_app
version: 1.0.0+1
publish_to: none
description: Schedules and other mobility types
environment: 
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  archive: ^3.1.2
  async: ^2.11.0
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  external_app_launcher: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_typeahead: ^4.6.2
  http: ^0.13.5
  intl: ^0.18.1
  json_serializable: ^6.7.0
  latlong2: ^0.8.1
  mockito: ^5.4.2
  path_provider: ^2.0.15
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.11
  very_good_analysis: ^5.0.0+1

dev_dependencies: 
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.3
flutter: 
  assets: 
    - assets/scooter.png
    - assets/bicycle.png
    - assets/bus.png
    - assets/scooter_low_battery.png
    - assets/county_bus.png
  uses-material-design: true
