name: Mobility App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Create .env file
        run: |
          echo "// ignore_for_file:non_constant_identifier_names" > lib/utils/env/env.dart
          echo "// ignore_for_file:constant_identifier_names" >> lib/utils/env/env.dart
          echo "// ignore_for_file:public_member_api_docs" >> lib/utils/env/env.dart
          echo "class Env {" >> lib/utils/env/env.dart
          echo "static const BOLT_TOKEN = '${{ secrets.BOLT_TOKEN }}';" >> lib/utils/env/env.dart
          echo "static const HOOG_TOKEN = '${{ secrets.HOOG_TOKEN }}';" >> lib/utils/env/env.dart
          echo "static const APP_PUBLIC_KEY = '${{ secrets.APP_PUBLIC_KEY }}';" >> lib/utils/env/env.dart
          echo "static const MAP_BOX_TOKEN = '${{ secrets.MAP_BOX_TOKEN }}';" >> lib/utils/env/env.dart
          echo "}" >> lib/utils/env/env.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart pub run build_runner build

      # Decode the keystore from base64 and place it
      - name: Decode keystore file
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./android/app/key.jks

      - name: Show current directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      # Set an environment variable to be used in build.gradle
      - name: Set Keystore Path
        run: echo "KEYSTORE_PATH=./key.jks" >> $GITHUB_ENV

      - name: Show current directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      # Build for debug
      #      - name: Build
      #        run: flutter build apk --flavor production --debug --target=lib/main_production.dart --split-per-abi
      # Build for release
      - name: Build apk
        run: flutter build apk --flavor production --release --target=lib/main_production.dart

#      - name: Build for web
#        run: flutter build web --release --base-href /Yggert-nu/ --target lib/main_production.dart
#
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: build/web # The folder the action should deploy.
#          target-folder: docs

      # - name: Test
      #   run: flutter test --flavor production

      #      - name: Run integration tests
      #        uses: reactivecircus/android-emulator-runner@v2
      #        with:
      #          api-level: 29
      #          arch: x86_64
      #          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #          profile: Nexus 6
      #          script: |
      #            flutter test --flavor production integration_test/onboarding_test.dart
      #            flutter test --flavor production integration_test/intro_test.dart
      # - name: Analyze
      #   run: flutter analyze
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/production/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.GITHUB_TOKEN }}