name: Mobility App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --target=lib/main_production.dart

      - name: Test
        run: flutter test

      - name: Set windows config
        run: |
          flutter config --enable-windows-desktop
          flutter test -d windows integration_test/intro_test.dart
          flutter test -d windows integration_test/onboarding_test.dart

      - name: Analyze
        run: flutter analyze
