name: Mobility App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Create .env file
        run: |
          echo "class Env {" > lib/utils/env/env.dart
          echo "static const BOLT_TOKEN = '${{ secrets.BOLT_TOKEN }}';" >> lib/utils/env/env.dart
          echo "static const HOOG_TOKEN = '${{ secrets.HOOG_TOKEN }}';" >> lib/utils/env/env.dart
          echo "static const APP_PUBLIC_KEY = '${{ secrets.APP_PUBLIC_KEY }}';" >> lib/utils/env/env.dart
          echo "static const MAP_BOX_TOKEN = '${{ secrets.MAP_BOX_TOKEN }}';" >> lib/utils/env/env.dart
          echo "}" >> lib/utils/env/env.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart pub run build_runner build

      - name: Build
        run: flutter build apk --flavor production --target=lib/main_production.dart

      - name: Test
        run: flutter test --flavor production

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter test --flavor production integration_test
      - name: Analyze
        run: flutter analyze
